version: "3.8"
services:
  app:
    build:
      context: .
      target: base
    ports:
      - "1919:1919"
    env_file:
      - .env.${ENV} # Dynamically load environment file based on ENV variable
    secrets:
      - mongo_url
      - secret_key
      - twilio_account_sid
      - twilio_auth_token
    volumes:
      - app-data:/usr/src/app/data # Persistent storage if needed
    networks:
      - private-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1919/health"]
      interval: 30s
      timeout: 10s
      retries: 3

secrets:
  mongo_url:
    file: ./secrets/mongo_url.txt
  secret_key:
    file: ./secrets/secret_key.txt
  twilio_account_sid:
    file: ./secrets/twilio_account_sid.txt
  twilio_auth_token:
    file: ./secrets/twilio_auth_token.txt

networks:
  private-network:
    driver: bridge

volumes:
  app-data:
